//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libraryCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class book_thirupa
    {
        public int bookid { get; set; }
        public string bookname { get; set; }
        public Nullable<int> bookpages { get; set; }
        public string bookauthor { get; set; }
        public Nullable<int> bookedition { get; set; }
        public Nullable<int> bookyearofpublish { get; set; }
        public Nullable<int> numberofcopies { get; set; }
    }
}
