//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libraryCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class borrowdetails_thirupa
    {
        public int Studentid { get; set; }
        public string bookname { get; set; }
        public System.DateTime bookborrowdate { get; set; }
        public Nullable<System.DateTime> bookreturndate { get; set; }
    
        public virtual borrowdetails_thirupa borrowdetails_thirupa1 { get; set; }
        public virtual borrowdetails_thirupa borrowdetails_thirupa2 { get; set; }
    }
}
