//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libraryCRUD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class appdev_trainingDb : DbContext
    {
        public appdev_trainingDb()
            : base("name=appdev_trainingDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<book_thirupa> book_thirupa { get; set; }
        public virtual DbSet<student_detail_thirupa> student_detail_thirupa { get; set; }
        public virtual DbSet<borrowdetails_thirupa> borrowdetails_thirupa { get; set; }
    }
}
