//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libraryCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_detail_thirupa
    {
        public int studentid { get; set; }
        public string studentname { get; set; }
        public string st_depart { get; set; }
        public string st_email { get; set; }
    
        public virtual student_detail_thirupa student_detail_thirupa1 { get; set; }
        public virtual student_detail_thirupa student_detail_thirupa2 { get; set; }
    }
}
